- name: Converge
  hosts: all
  vars:
    influxdb_docker_image_version: latest
    influxdb_docker_memory: 1G
    influxdb_docker_labels:
      maintainer: me@example.com
    influxdb_docker_network: internal
    influxdb_backup_path: /var/backups/influxdb
    influxdb_data_path: /var/lib/influxdb
    influxdb_etc_path: /etc/influxdb
    influxdb_env_vars:
      INFLUXD_REPORTING_DISABLED: "true"
    influxdb_primary_user: admin
    influxdb_primary_user_password: influxdb
    influxdb_primary_organization_name: my-org
    influxdb_primary_bucket_name: my-bucket
    influxdb_primary_bucket_name_retention_period: 0
    influxdb_users:
      - name: user1
        password: pass1234
    influxdb_buckets:
      - name: new-bucket
        description: A new bucket
        retention: 1h
    influxdb_authorizations:
      - user: user1
        description: user1 token with all permissions
        permissions:
          - read-buckets
          - write-buckets
  roles:
    - role: ansible-raspberry-influxdb-docker
      tags: influxdb
  post_tasks:
    - name: Create marker file for restore
      ansible.builtin.copy:
        dest: /var/tmp/ALLOW_RESTORE_OF_INFLUXDB
        content: ""
